# Generated by Django 5.0.6 on 2024-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
