# Generated by Django 5.0.6 on 2024-06-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportproduct_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportproduct',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
