# Generated by Django 5.0.6 on 2024-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportproduct_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproduct',
            name='quantity_not_found',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
