# Generated by Django 5.0.6 on 2024-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportproduct_quantity_not_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Report', max_length=255),
        ),
    ]
