# Generated by Django 5.0.6 on 2024-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='products',
            field=models.ManyToManyField(through='reports.ReportProduct', to='reports.product'),
        ),
    ]
